pick:	
	g++ ik_pickup_control.cpp ../src/JHPWMPCA9685.cpp -I ../src -o ../build/ik_pickup -O2 -larmadillo
mic:
	g++ motor_interface_control.cpp ../src/JHPWMPCA9685.cpp -I ../src -o ../build/m_interface -O2 -larmadillo
ik:
	g++ ik_interface_control.cpp ../src/JHPWMPCA9685.cpp -I ../src -o ../build/ik_interface -O2 -larmadillo
cali:
	g++ cali_test.cpp ../src/JHPWMPCA9685.cpp -I ../src -o ../build/cali
reset:
	g++ reset.cpp ../src/JHPWMPCA9685.cpp -I ../src -o ../build/reset -O2 -larmadillo
help:
	#mic,pick,reset,ik





##g++ test.cpp ../src/JHPWMPCA9685.cpp -I ../src -o ../build/test -O2 -larmadillo
#g++ ik_interface_control.cpp ../src/JHPWMPCA9685.cpp -I ../src -o ../build/ik_interface -O2 -larmadillo
#g++ cali_test.cpp ../src/JHPWMPCA9685.cpp -I ../src -o ../build/cali 
# g++ limited_inverse.cpp -o lim -O2 -larmadillo 
#g++ jacobian_inverse.cpp -o jac -O2 -larmadillo
#g++ motor_interface_control.cpp ../src/JHPWMPCA9685.cpp -I ../src -o ../build/m_interface -O2 -larmadillo
#g++ reset.cpp ../src/JHPWMPCA9685.cpp -I ../src -o ../build/reset -O2 -larmadillo
