all:	
	g++ motor_interface_control.cpp ../src/JHPWMPCA9685.cpp -I ../src -o ../build/mic -O2 -larmadillo
	# g++ limited_inverse.cpp -o lim -O2 -larmadillo 
	#g++ jacobian_inverse.cpp -o jac -O2 -larmadillo
	#g++ motor_interface_control.cpp -I ../src -o ../build/mic -O2 -larmadillo

